.gitignore
app/config/privateResources.php
app/config/services.php
app/library/Acl/Acl.php

Make the ACL more flexible bij having the private resources as a seperate config.

Added PrivateResources as config object

---

schemas/vokuro.sql

Password change userAgent to long error fix.
Tested only for MySQL!
For PostgreSQL shema not tested!

Password change userAgent to long error fix

---

app/controllers/PermissionsController.php

Update permissions by Search button press fix (controller part)

Update permissions by Search button press fix

---

app/views/permissions/index.volt

Update by Search button submit fix (template part)
Add anonter Submit button

Update by Search button submit fix

---

app/controllers/UsersController.php

Add validation (including email) when users updating and (or) creating

Add validation when users update and create

---

app/library/Auth/Auth.php

Allow to delete a token record in table "user_remember_tokens" after logout

Remove "user_remember_tokens" record after logout

---

README.md

Hello!
* Type: documentation
* Link to issue: #1
**In raising this pull request, I confirm the following (please check boxes):**
Small description of change:
Added information about permission on the directory
Thanks
[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md

Added info in README.md [ci skip]

---

app/views/layouts/public.volt

Hello!
* Type: code quality
* Link to issue: #25
**In raising this pull request, I confirm the following:**
Small description of change:
Added extra checking of variable `logged_in`
Thanks
[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md

Changed verification existence variable in layouts/public

---

app/models/Profiles.php

Hello!
* Type: new feature
* Link to issue: -
**In raising this pull request, I confirm the following:**
Small description of change:
Added deleting permissions when profile was deleted. Link to old PR https://github.com/phalcon/vokuro/pull/39
Thanks
[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md

Added deleting permissions when profile was deleted

---

app/library/Auth/Auth.php

UserRememberTokens does'nt exist, the code is adjusted to eliminate the token correctly.

Delete the user's token in session

---

CHANGELOG.md
schemas/upgrades/mysql-upgrade-to-1.3.0.sql
schemas/upgrades/postgresql-upgrade-to-1.3.0.sql
schemas/vokuro-mysql.sql
schemas/vokuro-postgresql.sql

Hello!
* Type: changing
* Link to issue: #83
**In raising this pull request, I confirm the following:**
Small description of change:
Changed column `userAgent` on type `TEXT`
Thanks
[:contrib:]: https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md

Changed column userAgent on type TEXT

---

app/views/about/index.volt
app/views/privacy/index.volt
app/views/terms/index.volt

Small commit converting Privacy, About and Terms pages to Bootstrap 4.1.1 .
This is in continuation of previous commit to convert whole vokuro frontend into BS 4.1.1, more changes on way.

Updated privacy, about and terms pages to Bootstrap 4.1.1

---

app/forms/ForgotPasswordForm.php
app/forms/LoginForm.php
app/forms/SignUpForm.php
app/views/session/forgotPassword.volt
app/views/session/login.volt
app/views/session/signup.volt

Updated
session/login 
session/forgotPassword 
session/signup to BS4.1.1
Changes includes 
* Use of new Email form element instead of Text, 
* Moved CSS classes to volt for better design control in views, 
* Added Label declaration to LoginForm.php so that can render label using volt only.

Update session/* areas to Bootstrap 4.1.1 

---

app/controllers/UsersController.php
app/forms/ChangePasswordForm.php
app/forms/UsersForm.php
app/views/layouts/private.volt
app/views/users/changePassword.volt
app/views/users/create.volt
app/views/users/edit.volt
app/views/users/index.volt
app/views/users/search.volt

Updated "User" backend part and private.volt to Bootstrap 4.1.1, changes includes : 
* Added Labels to some form element so that can render using VOLT
* Added Email Form Element for Email Input
* Used volt to render <form> element instead of HTML
* Removed deprecated Tag::resetInput() from UsersController.php, replaced with appropriate $formObject->clear() method
More changes coming to convert vokuro to BS4 completely.
Refs: https://github.com/phalcon/vokuro/issues/58

Updated "User" Backened part to Bootstrap 4.1.1

---

app/views/permissions/index.volt

Converted permission/index.volt to Bootstrap 4.1.1 , with this commit, now vokuro is fully converted to BS4. If there is any improvement, will make another commit. 
Refs: https://github.com/phalcon/vokuro/issues/58

Converted permissions/index.volt to Bootstrap 4.1.1

---

.env.example
app/controllers/PermissionsController.php
app/controllers/ProfilesController.php
app/forms/LoginForm.php
app/forms/SignUpForm.php
app/views/about/index.volt
app/views/emailTemplates/confirmation.volt
app/views/emailTemplates/reset.volt
app/views/index.volt
app/views/index/index.volt
app/views/layouts/emailTemplates.volt
app/views/layouts/private.volt
app/views/layouts/public.volt
app/views/permissions/index.volt
app/views/privacy/index.volt
app/views/profiles/create.volt
app/views/profiles/edit.volt
app/views/profiles/index.volt
app/views/profiles/search.volt
app/views/session/forgotPassword.volt
app/views/session/login.volt
app/views/session/signup.volt
app/views/terms/index.volt
app/views/users/changePassword.volt
app/views/users/create.volt
app/views/users/edit.volt
app/views/users/index.volt
app/views/users/search.volt
public/css/style.css

[Iteration 3] v4.0-beta

---

.ci/install-phalcon.sh
.editorconfig
.env.example
.travis.yml
codeception.yml
composer.json
tests/_support/Helper/Acceptance.php
tests/acceptance.suite.yml

Unify Travis CI configuration

---

.dockerignore
Dockerfile
resources/Dockerfile

Added initial docker image

---

.ci/install-postgres.sh
.dockerignore
.gitattributes
.travis.yml
CONTRIBUTING.md
app/Plugins/Acl/Acl.php
app/Plugins/Auth/Auth.php
app/Plugins/Mail/Mail.php
db/.gitignore
resources/Dockerfile

- Use Injectable instead Plugin (see: https://github.com/phalcon/cphalcon/pull/14360)
- Cleaned up Docker image
- Cleaned up Travis CI configuration

Fixed compatibility with Phalcon 4.x 

---

src/Controllers/UsersController.php
src/Forms/ProfilesForm.php
src/Forms/SignUpForm.php
src/Forms/UsersForm.php
themes/vokuro/users/create.volt
themes/vokuro/users/edit.volt
themes/vokuro/users/index.volt

Controller and views
- Code refactor
- Fixes

Users refactor

---

db/migrations/20190825193331_create_permissions.php

Hi,
I find the action and resource limits not fitting my needs, and I think it will apply for other people as well.
+ for MySQL having varchar 16 vs 250 has exactly the same performance anyways
@Jeckerson can you please take a look, I haven't ever used any migrations and such, I am not sure this is the correct way to increase the limit even if you want to.

set permissions db resource and action to have varchar 245 4.0.x

---

src/Plugins/Auth/Auth.php

Condition based on which cookies is checked has been modified

Modify cookies expiry condition

---

src/Application.php

Since im testing  the vokuro project  i cannot test this on an sub-directory , i always have to re configure the document root on my webserver to point in out this on the folder where the vokuro project is ,... and this is very anoying.  
Note: you have to configure your .env file in this way APP_BASE_URI=/subfolder1/subfolder2/../subfolderN/YOURVOKURODIRECTORYNAME/ , look the path starts with slash (/) and ends with slash. 
This also works when the APP_BASE_URI its just one slash. please correct me if im re-inventing the wheel , because i cant no find any other fix about this issue.

Makes vokuro run on any subdirectory.
